# Generated by Django 4.2.23 on 2025-08-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generos.genero')),
            ],
        ),
    ]
