# Generated by Django 4.2.23 on 2025-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('Biografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='integrantes')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('estudiante', 'Estudiante'), ('mentor', 'Mentor'), ('profesor', 'Profesor')], max_length=20)),
                ('Biografia', models.TextField()),
                ('lugar_residencia', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='profesor')),
                ('proyectos', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sede principal', max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('mapa_embed', models.TextField(blank=True, help_text='Codigo iframe de google maps opcional')),
                ('horario', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
