# Generated by Django 4.2.23 on 2025-08-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='imagen',
        ),
    ]
